=== baraaMousaNew/sff-demo-1-enhance/xsd/RemittanceAdvice.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid XML Studio 1.0.8.0 (http://www.liquid-technologies.com) -->
<xs:schema xmlns:tns="http://www.haad.ae/DataDictionary/CommonTypes" elementFormDefault="qualified" version="2.0" id="RemittanceAdvice" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:import schemaLocation="CommonTypes.xsd" namespace="http://www.haad.ae/DataDictionary/CommonTypes"/>
  <xs:element name="Remittance.Advice">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Header">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="SenderID" type="tns:HeaderSenderID"/>
              <xs:element name="ReceiverID" type="tns:HeaderReceiverID"/>
              <xs:element name="TransactionDate" type="tns:HeaderTransactionDate"/>
              <xs:element name="RecordCount" type="tns:HeaderRecordCount"/>
              <xs:element name="DispositionFlag" type="tns:HeaderDispositionFlag"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Claim" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ID" type="tns:ClaimID"/>
              <xs:element name="IDPayer" type="tns:ClaimIDPayer"/>
              <xs:element name="ProviderID" type="tns:ClaimProviderID" minOccurs="0"/>
              <xs:element name="DenialCode" type="tns:ClaimDenialCode" minOccurs="0"/>
              <xs:element name="PaymentReference" type="tns:ClaimPaymentReference"/>
              <xs:element name="DateSettlement" type="tns:ClaimDateSettlement" minOccurs="0"/>
              <xs:element name="Encounter" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="FacilityID" type="tns:EncounterFacilityID" minOccurs="0"/>                    
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Activity" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="ID" type="tns:ActivityID" minOccurs="0"/>
                    <xs:element name="Start" type="tns:ActivityStart"/>
                    <xs:element name="Type" type="tns:ActivityType"/>
                    <xs:element name="Code" type="tns:ActivityCode"/>
                    <xs:element name="Quantity" type="tns:ActivityQuantity"/>
                    <xs:element name="Net" type="tns:ActivityNet"/>
                    <xs:element name="List" type="tns:ActivityList" minOccurs="0"/>
					<xs:element name="OrderingClinician" type="tns:ActivityOrderingClinician" minOccurs="0"/>
                    <xs:element name="Clinician" type="tns:ActivityClinician" minOccurs="0"/>
                    <xs:element name="PriorAuthorizationID" type="tns:ActivityPriorAuthorizationID" minOccurs="0"/>
                    <xs:element name="Gross" type="tns:ActivityGross" minOccurs="0"/>
                    <xs:element name="PatientShare" type="tns:ActivityPatientShare" minOccurs="0"/>
                    <xs:element name="PaymentAmount" type="tns:ActivityPaymentAmount"/>
                    <xs:element name="DenialCode" type="tns:ActivityDenialCode" minOccurs="0"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== baraaMousaNew/sff-demo-1-enhance/allure-results/db637cbc-454c-414b-bc09-5d1b3d53b469-attachment.xml
<Remittance.Advice xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.haad.ae/DataDictionary/CommonTypes/RemittanceAdvice.xsd">
  <Header>
    <SenderID>T001_Malaffi</SenderID>
    <ReceiverID>TF001_Malaffi</ReceiverID>
    <TransactionDate>{{DATE(DD/MM/YYYY)}} 01:00</TransactionDate>
    <RecordCount>1</RecordCount>
    <DispositionFlag>PRODUCTION</DispositionFlag>
  </Header>
  <Claim>
    <ID>{{VAR(claim_id).CUSTOM.generate_numbers_id()}}</ID>
    <IDPayer>{{CUSTOM.generate_numbers_id(T001_Malaffi)}}</IDPayer>
	<ProviderID>TF001_Malaffi</ProviderID>
    <DenialCode />
    <PaymentReference>1111155555</PaymentReference>
	<DateSettlement>{{CUSTOM.add_minutes_to_current_date_time(2)}}</DateSettlement>
    <Encounter>
        <FacilityID>MF3505</FacilityID>
    </Encounter>
    <Activity>
	  <ID>{{VAR(activity_id).CUSTOM.generate_numbers_id()}}</ID>
      <Start>{{CUSTOM.get_current_date_time()}}</Start>
      <Type>3</Type>
      <Code>44950</Code>
      <Quantity>1</Quantity>
      <Net>0</Net>
      <List>0</List>
	  <OrderingClinician>GD6476</OrderingClinician>
      <Clinician>GD6476</Clinician>
      <PriorAuthorizationID />
      <Gross>100</Gross>
      <PatientShare>0</PatientShare>
      <PaymentAmount>0</PaymentAmount>
      <DenialCode />
    </Activity>
  </Claim>
</Remittance.Advice>

=== baraaMousaNew/sff-demo-1-enhance/xml_templates/remittance_advice_tkbk_2_template.xml
<?xml version="1.0" encoding="utf-8"?>
<Remittance.Advice xmlns:tns="http://www.haad.ae/DataDictionary/CommonTypes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.haad.ae/DataDictionary/CommonTypes/RemittanceAdvice.xsd">
  <Header>
    <SenderID>T001_Malaffi</SenderID>
    <ReceiverID>TF001_Malaffi</ReceiverID>
    <TransactionDate>{{DATE(DD/MM/YYYY)}} 01:00</TransactionDate>
    <RecordCount>1</RecordCount>
    <DispositionFlag>PRODUCTION</DispositionFlag>
  </Header>
  <Claim>
    <ID>{{VAR.claim_id}}</ID>
    <IDPayer>{{VAR.remittance_id_payer}}</IDPayer>
	<ProviderID>TF001_Malaffi</ProviderID>
    <DenialCode></DenialCode>
    <PaymentReference>1111155555</PaymentReference>
	<DateSettlement>{{CUSTOM.add_minutes_to_current_date_time(2)}}</DateSettlement>
    <Encounter>
        <FacilityID>{{VAR.facility_id}}</FacilityID>
    </Encounter>
    <Activity>
	  <ID>{{VAR.activity_id}}</ID>
      <Start>{{CUSTOM.get_current_date_time()}}</Start>
      <Type>3</Type>
      <Code>{{VAR.activity_code}}</Code>
      <Quantity>1.006</Quantity>
      <Net>1500.002</Net>
      <List>1500.002</List>
	  <OrderingClinician>{{VAR.clinician_license}}</OrderingClinician>
      <Clinician>{{VAR.clinician_license}}</Clinician>
      <PriorAuthorizationID></PriorAuthorizationID>
      <Gross>1500.002</Gross>
      <PatientShare>0</PatientShare>
      <PaymentAmount>-110</PaymentAmount>
      <DenialCode>TKBK-002</DenialCode>
    </Activity>
  </Claim>
</Remittance.Advice>

=== baraaMousaNew/sff-demo-1-enhance/allure-results/b99bde4e-eafd-47c4-a45a-2c7b2bf76b3a-attachment.xml
<Remittance.Advice xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.haad.ae/DataDictionary/CommonTypes/RemittanceAdvice.xsd">
  <Header>
    <SenderID>T001_Malaffi</SenderID>
    <ReceiverID>TF001_Malaffi</ReceiverID>
    <TransactionDate>23/09/2026 01:00</TransactionDate>
    <RecordCount>1</RecordCount>
    <DispositionFlag>PRODUCTION</DispositionFlag>
  </Header>
  <Claim>
    <ID>3662459031</ID>
    <IDPayer>T001_Malaffi-1365863538</IDPayer>
	<ProviderID>TF001_Malaffi</ProviderID>
    <DenialCode />
    <PaymentReference>1111155555</PaymentReference>
	<DateSettlement>23/09/2026 12:33</DateSettlement>
    <Encounter>
        <FacilityID>MF3505</FacilityID>
    </Encounter>
    <Activity>
	  <ID>1425272308</ID>
      <Start>23/09/2026 12:31</Start>
      <Type>3</Type>
      <Code>44950</Code>
      <Quantity>1</Quantity>
      <Net>0</Net>
      <List>0</List>
	  <OrderingClinician>GD6476</OrderingClinician>
      <Clinician>GD6476</Clinician>
      <PriorAuthorizationID />
      <Gross>100</Gross>
      <PatientShare>0</PatientShare>
      <PaymentAmount>0</PaymentAmount>
      <DenialCode />
    </Activity>
  </Claim>
</Remittance.Advice>

=== baraaMousaNew/sff-demo-1-enhance/xml_templates/remittance_advice_tkbk_template.xml
<?xml version="1.0" encoding="utf-8"?>
<Remittance.Advice xmlns:tns="http://www.haad.ae/DataDictionary/CommonTypes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.haad.ae/DataDictionary/CommonTypes/RemittanceAdvice.xsd">
  <Header>
    <SenderID>T001_Malaffi</SenderID>
    <ReceiverID>TF001_Malaffi</ReceiverID>
    <TransactionDate>{{DATE(DD/MM/YYYY)}} 01:00</TransactionDate>
    <RecordCount>1</RecordCount>
    <DispositionFlag>PRODUCTION</DispositionFlag>
  </Header>
  <Claim>
    <ID>{{VAR.claim_id}}</ID>
    <IDPayer>{{VAR(remittance_id_payer).CUSTOM.generate_numbers_id(T001_Malaffi)}}</IDPayer>
	<ProviderID>TF001_Malaffi</ProviderID>
    <DenialCode></DenialCode>
    <PaymentReference>1111155555</PaymentReference>
	<DateSettlement>{{CUSTOM.add_minutes_to_current_date_time(2)}}</DateSettlement>
    <Encounter>
        <FacilityID>MF3505</FacilityID>
    </Encounter>
    <Activity>
	  <ID>{{VAR.activity_id}}</ID>
      <Start>{{DATE(DD/MM/YYYY)}} 13:00</Start>
      <Type>3</Type>
      <Code>44950</Code>
      <Quantity>1</Quantity>
      <Net>0</Net>
      <List>0</List>
	  <OrderingClinician>GD6476</OrderingClinician>
      <Clinician>GD6476</Clinician>
      <PriorAuthorizationID></PriorAuthorizationID>
      <Gross>100</Gross>
      <PatientShare>0</PatientShare>
      <PaymentAmount>0</PaymentAmount>
      <DenialCode></DenialCode>
    </Activity>
  </Claim>
</Remittance.Advice>

=== baraaMousaNew/sff-demo-1-enhance/xml_templates/remittance_advice_multiple_template.xml
<?xml version="1.0" encoding="utf-8"?>
<Remittance.Advice xmlns:tns="http://www.haad.ae/DataDictionary/CommonTypes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.haad.ae/DataDictionary/CommonTypes/RemittanceAdvice.xsd">
  <Header>
    <SenderID>T001_Malaffi</SenderID>
    <ReceiverID>TF001_Malaffi</ReceiverID>
    <TransactionDate>{{DATE(DD/MM/YYYY)}} 01:00</TransactionDate>
    <RecordCount>5</RecordCount>
    <DispositionFlag>PRODUCTION</DispositionFlag>
  </Header>
  <Claim>
    <ID>{{VAR.claim_id_one}}</ID>
    <IDPayer>{{VAR(remittance_id_payer).CUSTOM.generate_numbers_id(T001_Malaffi)}}</IDPayer>
	<ProviderID>TF001_Malaffi</ProviderID>
    <DenialCode></DenialCode>
    <PaymentReference>1111155555</PaymentReference>
	<DateSettlement>{{CUSTOM.add_minutes_to_current_date_time(2)}}</DateSettlement>
    <Encounter>
        <FacilityID>{{VAR.facility_id}}</FacilityID>
    </Encounter>
    <Activity>
          <ID>1</ID>
          <Start>{{CUSTOM.sub_days_to_current_date(60)}} 15:40</Start>
          <Type>5</Type>
          <Code>QD4-C900-16948-01</Code>
          <Quantity>1.0000</Quantity>
          <Net>197590.00</Net>
          <OrderingClinician>GD25888</OrderingClinician>
          <Clinician>GD25888</Clinician>
          <PriorAuthorizationID>MF3505-{{VAR.prior_request_id}}</PriorAuthorizationID>
          <PaymentAmount>197590.00</PaymentAmount>
          <DenialCode></DenialCode>
        </Activity>
  </Claim>
  <Claim>
    <ID>{{VAR.claim_id_two}}</ID>
    <IDPayer>{{VAR(remittance_id_payer).CUSTOM.generate_numbers_id(T001_Malaffi)}}</IDPayer>
	<ProviderID>TF001_Malaffi</ProviderID>
    <DenialCode></DenialCode>
    <PaymentReference>1111155555</PaymentReference>
	<DateSettlement>{{CUSTOM.add_minutes_to_current_date_time(2)}}</DateSettlement>
    <Encounter>
        <FacilityID>{{VAR.facility_id}}</FacilityID>
    </Encounter>
    <Activity>
          <ID>1</ID>
          <Start>{{CUSTOM.sub_days_to_current_date(60)}} 15:40</Start>
          <Type>5</Type>
          <Code>QD4-C900-16948-01</Code>
          <Quantity>1.0000</Quantity>
          <Net>197590.00</Net>
          <OrderingClinician>GD25888</OrderingClinician>
          <Clinician>GD25888</Clinician>
          <PriorAuthorizationID>MF3505-{{VAR.prior_request_id}}</PriorAuthorizationID>
          <PaymentAmount>197590.00</PaymentAmount>
          <DenialCode></DenialCode>
        </Activity>
  </Claim>
  <Claim>
    <ID>{{VAR.claim_id_three}}</ID>
    <IDPayer>{{VAR(remittance_id_payer).CUSTOM.generate_numbers_id(T001_Malaffi)}}</IDPayer>
	<ProviderID>TF001_Malaffi</ProviderID>
    <DenialCode></DenialCode>
    <PaymentReference>1111155555</PaymentReference>
	<DateSettlement>{{CUSTOM.add_minutes_to_current_date_time(2)}}</DateSettlement>
    <Encounter>
        <FacilityID>{{VAR.facility_id}}</FacilityID>
    </Encounter>
    <Activity>
          <ID>1</ID>
          <Start>{{CUSTOM.sub_days_to_current_date(60)}} 15:40</Start>
          <Type>5</Type>
          <Code>QD4-C900-16948-01</Code>
          <Quantity>1.0000</Quantity>
          <Net>197590.00</Net>
          <OrderingClinician>GD25888</OrderingClinician>
          <Clinician>GD25888</Clinician>
          <PriorAuthorizationID>MF3505-{{VAR.prior_request_id}}</PriorAuthorizationID>
          <PaymentAmount>197590.00</PaymentAmount>
          <DenialCode></DenialCode>
        </Activity>
  </Claim>
  <Claim>
    <ID>{{VAR.claim_id_four}}</ID>
    <IDPayer>{{VAR(remittance_id_payer).CUSTOM.generate_numbers_id(T001_Malaffi)}}</IDPayer>
	<ProviderID>TF001_Malaffi</ProviderID>
    <DenialCode></DenialCode>
    <PaymentReference>1111155555</PaymentReference>
	<DateSettlement>{{CUSTOM.add_minutes_to_current_date_time(2)}}</DateSettlement>
    <Encounter>
        <FacilityID>{{VAR.facility_id}}</FacilityID>
    </Encounter>
    <Activity>
          <ID>1</ID>
          <Start>{{CUSTOM.sub_days_to_current_date(60)}} 15:40</Start>
          <Type>5</Type>
          <Code>QD4-C900-16948-01</Code>
          <Quantity>1.0000</Quantity>
          <Net>197590.00</Net>
          <OrderingClinician>GD25888</OrderingClinician>
          <Clinician>GD25888</Clinician>
          <PriorAuthorizationID>MF3505-{{VAR.prior_request_id}}</PriorAuthorizationID>
          <PaymentAmount>197590.00</PaymentAmount>
          <DenialCode></DenialCode>
        </Activity>
  </Claim>
  <Claim>
    <ID>{{VAR.claim_id_five}}</ID>
    <IDPayer>{{VAR(remittance_id_payer).CUSTOM.generate_numbers_id(T001_Malaffi)}}</IDPayer>
	<ProviderID>TF001_Malaffi</ProviderID>
    <DenialCode></DenialCode>
    <PaymentReference>1111155555</PaymentReference>
	<DateSettlement>{{CUSTOM.add_minutes_to_current_date_time(2)}}</DateSettlement>
    <Encounter>
        <FacilityID>{{VAR.facility_id}}</FacilityID>
    </Encounter>
    <Activity>
          <ID>1</ID>
          <Start>{{CUSTOM.sub_days_to_current_date(60)}} 15:40</Start>
          <Type>5</Type>
          <Code>QD4-C900-16948-01</Code>
          <Quantity>1.0000</Quantity>
          <Net>197590.00</Net>
          <OrderingClinician>GD25888</OrderingClinician>
          <Clinician>GD25888</Clinician>
          <PriorAuthorizationID>MF3505-{{VAR.prior_request_id}}</PriorAuthorizationID>
          <PaymentAmount>197590.00</PaymentAmount>
          <DenialCode></DenialCode>
        </Activity>
  </Claim>
</Remittance.Advice>

=== baraaMousaNew/sff-demo-1-enhance/xml_templates/remittance_advice_multiple_activities_template.xml
<?xml version="1.0" encoding="utf-8"?>
<Remittance.Advice xmlns:tns="http://www.haad.ae/DataDictionary/CommonTypes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.haad.ae/DataDictionary/CommonTypes/RemittanceAdvice.xsd">
  <Header>
    <SenderID>T001_Malaffi</SenderID>
    <ReceiverID>TF001_Malaffi</ReceiverID>
    <TransactionDate>{{DATE(DD/MM/YYYY)}} 01:00</TransactionDate>
    <RecordCount>1</RecordCount>
    <DispositionFlag>PRODUCTION</DispositionFlag>
  </Header>
  <Claim>
    <ID>{{VAR.claim_id}}</ID>
    <IDPayer>{{VAR(remittance_id_payer).CUSTOM.generate_numbers_id(T001_Malaffi)}}</IDPayer>
	<ProviderID>TF001_Malaffi</ProviderID>
    <DenialCode></DenialCode>
    <PaymentReference>1111155555</PaymentReference>
	<DateSettlement>{{CUSTOM.add_minutes_to_current_date_time(2)}}</DateSettlement>
    <Encounter>
        <FacilityID>{{VAR.facility_id}}</FacilityID>
    </Encounter>
    <Activity>
	  <ID>{{VAR.activity_id_1}}</ID>
      <Start>{{CUSTOM.get_current_date_time()}}</Start>
      <Type>3</Type>
      <Code>{{VAR.activity_code_1}}</Code>
      <Quantity>1.006</Quantity>
      <Net>1500.002</Net>
      <List>1500.002</List>
	  <OrderingClinician>{{VAR.clinician_license_1}}</OrderingClinician>
      <Clinician>{{VAR.clinician_license_1}}</Clinician>
      <PriorAuthorizationID></PriorAuthorizationID>
      <Gross>1500.002</Gross>
      <PatientShare>0</PatientShare>
      <PaymentAmount>1500.002</PaymentAmount>
      <DenialCode></DenialCode>
    </Activity>
    <Activity>
	  <ID>{{VAR.activity_id_2}}</ID>
      <Start>{{CUSTOM.get_current_date_time()}}</Start>
      <Type>3</Type>
      <Code>{{VAR.activity_code_2}}</Code>
      <Quantity>1.006</Quantity>
      <Net>1500.002</Net>
      <List>1500.002</List>
	  <OrderingClinician>{{VAR.clinician_license_2}}</OrderingClinician>
      <Clinician>{{VAR.clinician_license_2}}</Clinician>
      <PriorAuthorizationID></PriorAuthorizationID>
      <Gross>1500.002</Gross>
      <PatientShare>0</PatientShare>
      <PaymentAmount>1500.002</PaymentAmount>
      <DenialCode></DenialCode>
    </Activity>
  </Claim>
</Remittance.Advice>

=== baraaMousaNew/sff-demo-1-enhance/xml_templates/remittance_advice_multiple_template_isolated.xml
<?xml version="1.0" encoding="utf-8"?>
<Remittance.Advice xmlns:tns="http://www.haad.ae/DataDictionary/CommonTypes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.haad.ae/DataDictionary/CommonTypes/RemittanceAdvice.xsd">
  <Header>
    <SenderID>T001_Malaffi</SenderID>
    <ReceiverID>TF001_Malaffi</ReceiverID>
    <TransactionDate>{{DATE(DD/MM/YYYY)}} 01:00</TransactionDate>
    <RecordCount>5</RecordCount>
    <DispositionFlag>PRODUCTION</DispositionFlag>
  </Header>
  <Claim>
    <ID>{{VAR(claim_id_one).CUSTOM.generate_claim_id(MF3505)}}</ID>
    <IDPayer>{{VAR(remittance_id_payer).CUSTOM.generate_numbers_id(T001_Malaffi)}}</IDPayer>
	<ProviderID>TF001_Malaffi</ProviderID>
    <DenialCode></DenialCode>
    <PaymentReference>1111155555</PaymentReference>
	<DateSettlement>{{CUSTOM.add_minutes_to_current_date_time(2)}}</DateSettlement>
    <Encounter>
        <FacilityID>MF3505</FacilityID>
    </Encounter>
    <Activity>
          <ID>1</ID>
          <Start>{{CUSTOM.sub_days_to_current_date(60)}} 15:40</Start>
          <Type>5</Type>
          <Code>QD4-C900-16948-01</Code>
          <Quantity>1.0000</Quantity>
          <Net>197590.00</Net>
          <OrderingClinician>GD25888</OrderingClinician>
          <Clinician>GD25888</Clinician>
          <PriorAuthorizationID>MF3505-{{CUSTOM.generate_numbers_id()}}</PriorAuthorizationID>
          <PaymentAmount>197590.00</PaymentAmount>
          <DenialCode></DenialCode>
        </Activity>
  </Claim>
  <Claim>
    <ID>{{VAR(claim_id_two).CUSTOM.generate_claim_id(MF3505)}}</ID>
    <IDPayer>{{VAR(remittance_id_payer).CUSTOM.generate_numbers_id(T001_Malaffi)}}</IDPayer>
	<ProviderID>TF001_Malaffi</ProviderID>
    <DenialCode></DenialCode>
    <PaymentReference>1111155555</PaymentReference>
	<DateSettlement>{{CUSTOM.add_minutes_to_current_date_time(2)}}</DateSettlement>
    <Encounter>
        <FacilityID>MF3505</FacilityID>
    </Encounter>
    <Activity>
          <ID>1</ID>
          <Start>{{CUSTOM.sub_days_to_current_date(60)}} 15:40</Start>
          <Type>5</Type>
          <Code>QD4-C900-16948-01</Code>
          <Quantity>1.0000</Quantity>
          <Net>197590.00</Net>
          <OrderingClinician>GD25888</OrderingClinician>
          <Clinician>GD25888</Clinician>
          <PriorAuthorizationID>MF3505-{{CUSTOM.generate_numbers_id()}}</PriorAuthorizationID>
          <PaymentAmount>197590.00</PaymentAmount>
          <DenialCode></DenialCode>
        </Activity>
  </Claim>
  <Claim>
    <ID>{{VAR(claim_id_three).CUSTOM.generate_claim_id(MF3505)}}</ID>
    <IDPayer>{{VAR(remittance_id_payer).CUSTOM.generate_numbers_id(T001_Malaffi)}}</IDPayer>
	<ProviderID>TF001_Malaffi</ProviderID>
    <DenialCode></DenialCode>
    <PaymentReference>1111155555</PaymentReference>
	<DateSettlement>{{CUSTOM.add_minutes_to_current_date_time(2)}}</DateSettlement>
    <Encounter>
        <FacilityID>MF3505</FacilityID>
    </Encounter>
    <Activity>
          <ID>1</ID>
          <Start>{{CUSTOM.sub_days_to_current_date(60)}} 15:40</Start>
          <Type>5</Type>
          <Code>QD4-C900-16948-01</Code>
          <Quantity>1.0000</Quantity>
          <Net>197590.00</Net>
          <OrderingClinician>GD25888</OrderingClinician>
          <Clinician>GD25888</Clinician>
          <PriorAuthorizationID>MF3505-{{CUSTOM.generate_numbers_id()}}</PriorAuthorizationID>
          <PaymentAmount>197590.00</PaymentAmount>
          <DenialCode></DenialCode>
        </Activity>
  </Claim>
  <Claim>
    <ID>{{VAR(claim_id_four).CUSTOM.generate_claim_id(MF3505)}}</ID>
    <IDPayer>{{VAR(remittance_id_payer).CUSTOM.generate_numbers_id(T001_Malaffi)}}</IDPayer>
	<ProviderID>TF001_Malaffi</ProviderID>
    <DenialCode></DenialCode>
    <PaymentReference>1111155555</PaymentReference>
	<DateSettlement>{{CUSTOM.add_minutes_to_current_date_time(2)}}</DateSettlement>
    <Encounter>
        <FacilityID>MF3505</FacilityID>
    </Encounter>
    <Activity>
          <ID>1</ID>
          <Start>{{CUSTOM.sub_days_to_current_date(60)}} 15:40</Start>
          <Type>5</Type>
          <Code>QD4-C900-16948-01</Code>
          <Quantity>1.0000</Quantity>
          <Net>197590.00</Net>
          <OrderingClinician>GD25888</OrderingClinician>
          <Clinician>GD25888</Clinician>
          <PriorAuthorizationID>MF3505-{{CUSTOM.generate_numbers_id()}}</PriorAuthorizationID>
          <PaymentAmount>197590.00</PaymentAmount>
          <DenialCode></DenialCode>
        </Activity>
  </Claim>
  <Claim>
    <ID>{{VAR(claim_id_five).CUSTOM.generate_claim_id(MF3505)}}</ID>
    <IDPayer>{{VAR(remittance_id_payer).CUSTOM.generate_numbers_id(T001_Malaffi)}}</IDPayer>
	<ProviderID>TF001_Malaffi</ProviderID>
    <DenialCode></DenialCode>
    <PaymentReference>1111155555</PaymentReference>
	<DateSettlement>{{CUSTOM.add_minutes_to_current_date_time(2)}}</DateSettlement>
    <Encounter>
        <FacilityID>MF3505</FacilityID>
    </Encounter>
    <Activity>
          <ID>1</ID>
          <Start>{{CUSTOM.sub_days_to_current_date(60)}} 15:40</Start>
          <Type>5</Type>
          <Code>QD4-C900-16948-01</Code>
          <Quantity>1.0000</Quantity>
          <Net>197590.00</Net>
          <OrderingClinician>GD25888</OrderingClinician>
          <Clinician>GD25888</Clinician>
          <PriorAuthorizationID>MF3505-{{CUSTOM.generate_numbers_id()}}</PriorAuthorizationID>
          <PaymentAmount>197590.00</PaymentAmount>
          <DenialCode></DenialCode>
        </Activity>
  </Claim>
</Remittance.Advice>
